# Generated by cucumber-sinatra. (Wed May 25 23:29:21 -0700 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/harper.rb')
require File.join(File.dirname(__FILE__), 'client_application')

require 'sham_rack'
require 'rspec'

require File.join(File.dirname(__FILE__), '..', '..', 'spec/spec_helper')

class HarperWorld
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  HarperWorld.new
  ClientApplication.new
end

ShamRack.at("example.com").rackup do
  run Harper::App.new
end
